name: build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  tomcat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: tomcat
        directory: tomcat
        dockerfile: tomcat/Dockerfile
        tag: 8-jdk8
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: gradle
        directory: gradle
        dockerfile: gradle/Dockerfile
        tag: 5-jdk8
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: node
        directory: node
        dockerfile: node/Dockerfile
        tag: '10'
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
