name: gradle

on:
  push:
    branches:
    - main
    paths:
    - 'gradle/**'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: gradle
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/keecon/gradle:5-jdk8
