name: build minio

on:
  push:
    branches:
    - main
    paths:
    - 'minio/**'

jobs:
  minio-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: minio
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/keecon/minio:2021
          ghcr.io/keecon/minio:2021-06-17

  minio-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: minio
        file: minio/Dockerfile.client
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/keecon/minio-client:2021
          ghcr.io/keecon/minio-client:2021-06-17
