name: mssql

on:
  push:
    branches:
    - main
    paths:
    - 'mssql/**'
    - '.github/workflows/mssql.yml'

jobs:
  mssql-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: mssql
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/mssql:2022
          ghcr.io/keecon/mssql:2022-CU13
          ghcr.io/keecon/mssql:2022-CU13-ubuntu-22.04

  mssql-2019:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: mssql
        file: mssql/Dockerfile.2019
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/mssql:2019
          ghcr.io/keecon/mssql:2019-CU26
          ghcr.io/keecon/mssql:2019-CU26-ubuntu-20.04

  mssql-2017:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: mssql
        file: mssql/Dockerfile.2017
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/mssql:2017
          ghcr.io/keecon/mssql:2017-CU31
          ghcr.io/keecon/mssql:2017-CU31-ubuntu-18.04
