name: open-telemetry2

on:
  push:
    branches:
    - main
    paths:
    - 'open-telemetry/**'
    - '.github/workflows/open-telemetry2.yml'

env:
  OTEL_VERSION: v2.4.0

jobs:
  open-telemetry2-jdk21:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk21
        platforms: linux/amd64
        tags: ghcr.io/keecon/open-telemetry:2-jdk21
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry2-jdk17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk17
        platforms: linux/amd64
        tags: ghcr.io/keecon/open-telemetry:2-jdk17
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry2-jdk11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk11
        platforms: linux/amd64
        tags: ghcr.io/keecon/open-telemetry:2-jdk11
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry2-tomcat10-jdk17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.tomcat10.jdk17
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/keecon/open-telemetry:2-tomcat10-jdk17
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry2-tomcat9-jdk11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.tomcat9.jdk11
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/keecon/open-telemetry:2-tomcat9-jdk11
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}
