name: open-telemetry

on:
  push:
    branches:
    - main
    paths:
    - 'open-telemetry/**'
    - '.github/workflows/open-telemetry.yml'

env:
  OTEL_VERSION: v1.33.3

jobs:
  open-telemetry-jdk21:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk21
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/open-telemetry:jdk21
          ghcr.io/keecon/open-telemetry:1-jdk21
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry-jdk21-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk21-alpine
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/open-telemetry:jdk21-alpine
          ghcr.io/keecon/open-telemetry:1-jdk21-alpine
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry-jdk21-ffmpeg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk21-ffmpeg
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/open-telemetry:jdk21-ffmpeg
          ghcr.io/keecon/open-telemetry:1-jdk21-ffmpeg
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry-jdk17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk17
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/open-telemetry:jdk17
          ghcr.io/keecon/open-telemetry:1-jdk17
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry-jdk17-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk17-alpine
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/open-telemetry:jdk17-alpine
          ghcr.io/keecon/open-telemetry:1-jdk17-alpine
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry-jdk17-ffmpeg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk17-ffmpeg
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/open-telemetry:jdk17-ffmpeg
          ghcr.io/keecon/open-telemetry:1-jdk17-ffmpeg
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry-jdk11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk11
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/open-telemetry:jdk11
          ghcr.io/keecon/open-telemetry:1-jdk11
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry-tomcat10-jdk17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.tomcat10.jdk17
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/keecon/open-telemetry:tomcat10-jdk17
          ghcr.io/keecon/open-telemetry:1-tomcat10-jdk17
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}

  open-telemetry-tomcat9-jdk11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.tomcat9.jdk11
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/keecon/open-telemetry:tomcat9-jdk11
          ghcr.io/keecon/open-telemetry:1-tomcat9-jdk11
        build-args:
          OTEL_VERSION=${{ env.OTEL_VERSION }}
