name: open-telemetry-ffmpeg

on:
  push:
    branches:
    - main
    paths:
    - 'open-telemetry/**'
    - '.github/workflows/open-telemetry-ffmpeg.yml'

env:
  OTEL_VERSION: v1.33.1
  FFMPEG_VERSION: 6.1.1

jobs:
  open-telemetry-ffmpeg-jdk21:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk21-ffmpeg
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/open-telemetry:jdk21-ffmpeg
          ghcr.io/keecon/open-telemetry:1-jdk21-ffmpeg
        build-args: |
          OTEL_VERSION=${{ env.OTEL_VERSION }}
          FFMPEG_VERSION=${{ env.FFMPEG_VERSION }}

  open-telemetry-ffmpeg-jdk17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk17-ffmpeg
        platforms: linux/amd64
        tags: |
          ghcr.io/keecon/open-telemetry:jdk17-ffmpeg
          ghcr.io/keecon/open-telemetry:1-jdk17-ffmpeg
        build-args: |
          OTEL_VERSION=${{ env.OTEL_VERSION }}
          FFMPEG_VERSION=${{ env.FFMPEG_VERSION }}
