name: open-telemetry

on:
  push:
    branches:
    - main
    paths:
    - 'open-telemetry/**'

jobs:
  open-telemetry-jdk21:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk21
        platforms: linux/amd64
        tags: ghcr.io/keecon/open-telemetry:jdk21

  open-telemetry-jdk17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk17
        platforms: linux/amd64
        tags: ghcr.io/keecon/open-telemetry:jdk17

  open-telemetry-jdk11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.jdk11
        platforms: linux/amd64
        tags: ghcr.io/keecon/open-telemetry:jdk11

  open-telemetry-tomcat10-jdk17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.tomcat10.jdk17
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/keecon/open-telemetry:tomcat10-jdk17

  open-telemetry-tomcat9-jdk11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: open-telemetry/agent
        file: open-telemetry/agent/Dockerfile.tomcat9.jdk11
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/keecon/open-telemetry:tomcat9-jdk11
