name: postgres

on:
  push:
    branches:
    - main
    paths:
    - 'postgres/**'
    - '.github/workflows/postgres.yml'

jobs:
  postgres:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: postgres
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/keecon/postgres:14
          ghcr.io/keecon/postgres:14.6
