name: tcp-proxy

on:
  push:
    branches:
    - main
    paths:
    - 'tcp-proxy/**'

jobs:
  tcp-proxy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: tcp-proxy
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/keecon/tcp-proxy:1.0
          ghcr.io/keecon/tcp-proxy:1
          ghcr.io/keecon/tcp-proxy:latest
