FROM tomcat:9-jdk11-temurin

LABEL org.opencontainers.image.source https://github.com/keecon/docker-images

ARG INSTALL_URL=https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar

RUN rm -rf /usr/local/tomcat/webapps/*

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && mkdir -p /otel \
    && chmod -R o+x /otel \
    && curl -SL ${INSTALL_URL} -o /otel/opentelemetry-javaagent.jar \
    && rm -rf /var/lib/apt/lists/*
