FROM eclipse-temurin:25-jdk-alpine@sha256:5ecfde8e5ecde5954ea3721155b345ef56c1d579b940c761318ad4c05959a151

ARG OTEL_VERSION
ARG OTEL_SHA256
ARG OTEL_INSTALL_URL=https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v${OTEL_VERSION}/opentelemetry-javaagent.jar

LABEL org.opencontainers.image.source=https://github.com/keecon/docker-images
LABEL org.opencontainers.image.version=${OTEL_VERSION}
LABEL org.opencontainers.image.base.name=eclipse-temurin:25-jdk-alpine@sha256:5ecfde8e5ecde5954ea3721155b345ef56c1d579b940c761318ad4c05959a151

RUN test -n "${OTEL_VERSION}" \
    && test -n "${OTEL_SHA256}" \
    && apk add --no-cache curl \
    && install -d -m 0755 /otel \
    && curl --fail --show-error --silent --location --retry 3 \
        "${OTEL_INSTALL_URL}" \
        --output /otel/opentelemetry-javaagent.jar \
    && echo "${OTEL_SHA256}  /otel/opentelemetry-javaagent.jar" | sha256sum --check \
    && apk del curl

RUN java -version \
    && java -Xshare:off -javaagent:/otel/opentelemetry-javaagent.jar -version
