FROM tomcat:10-jdk17-temurin

LABEL org.opencontainers.image.source https://github.com/keecon/docker-images

ARG OTEL_VERSION=v1.32.1
ARG OTEL_INSTALL_URL=https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/${OTEL_VERSION}/opentelemetry-javaagent.jar

RUN rm -rf /usr/local/tomcat/webapps/*

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && mkdir -p /otel \
    && chmod -R o+x /otel \
    && curl -SL ${OTEL_INSTALL_URL} -o /otel/opentelemetry-javaagent.jar \
    && rm -rf /var/lib/apt/lists/*

